version: '3.7'
services:
  torrent:
    container_name: qbittorent-vpn
    image: markusmcnugen/qbittorrentvpn
    ports:
      - 8080:8080
      - 6969:6969
      - 6969:6969/udp
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    privileged: true
    volumes:
      - ./torrent:/config
      - ./media:/downloads
    environment:
      VPN_ENABLED: 'yes'
      LAN_NETWORK: 192.168.1.0/24
      NAME_SERVERS: 8.8.8.8,8.8.4.4
      INCOMING_PORT_ENV: 6969