version: '3.3'
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    # environment:
    volumes:
      - /home/udocker/volumes/jellyfin/:/config
      - /home/udocker/volumes/jellyfin/tvshows:/data/tvshows
      - /home/udocker/volumes/jellyfin/movies:/data/movies
      - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
      - /dev/vchiq:/dev/vchiq #optional
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=jellyfin"    