version: "3"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    user: udocker
    environment:
      - PUID: "${UDOCKER_USERID}"
      - PGID: "${UDOCKER_GROUPID}"
      - TZ: "${TZ}"
    volumes:
      - /home/udocker/volumes/duplicati/config:/config
      - /home/udocker/volumes/duplicati/backups:/backups
      - /home/udocker/volumes/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
        - "AIS.traefik=false"
        - "AIS.name=deluge"