version: "3.3"
services:
    .template:
        image: .template
        container_name: .template
        user: udocker
        environment:
            - PUID: ${userid}
            - PGID: ${groupid}
            - TZ: ${time}
        volumes:
            - /home/udocker/volumes/.template:/home/template
        ports:
            - 8080:8080
        restart: unless-stopped
        labels:
            - "AIS.traefik=false"
            - "AIS.name=.template"
