sudo: false

language: bash
env: PATH=${PATH}:${HOME}/kcov
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - build-essential
      - bats
      - bc
      
before_install:
  # install all the submodules
  - git submodule update --init --recursive
  - git pull --recurse-submodules
  - git submodule update --remote

script:
  - cd tests
  - bash coverage.sh
  - cd ..
  - cd docs
  - bash generate_docs.sh docs.sh
  - cd ..

# after_success:
  # - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false