language: shell
jobs:
  include:
    - os: linux
      dist: trusty
      arch: amd64
    - os: linux
      dist: trusty
      arch: arm64
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: arm64

cache:
  directories:
    - tests/bin
    - tests/coverage

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - build-essential
      - bats
      - bc
      - ruby-full

before_install:
  - gem install awesome_bot

script:
  - cd tests || exit 1
  - sudo bash linter.sh # linter shellcheck
  # - sudo bash tests.sh # test
  # - sudo bash coverage.sh # coverage kcov
  - cd .. || exit 1
  - cd docs/scripts || exit 1
  - bash generate_docs.sh ../docs.md # documentation shdoc
  - cd ../.. || exit 1
  - awesome_bot README.md --allow-dupe --allow-redirect --allow-ssl --allow-timeout --allow 999,403,405,500,503,522

notifications:
    email: false