language: shell
jobs:
  include:
    - os: linux
      dist: trusty
      arch: amd64
    - os: linux
      dist: trusty
      arch: arm64
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: xenial
      arch: amd64
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: arm64
    # - os: linux
    #   dist: disco
    # - os: linux
    #   dist: comic
    # - os: linux
    #   dist: eoan
    # - os: linux
    #   dist: focal

cache:
  directories:
    - tests/bin
    - tests/coverage

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - build-essential
      - bats
      - bc
      
# before_install:

script:
  - cd tests || exit 1
  - bash linter.sh # linter shellcheck
  - bash tests.sh # coverage kcov
  - bash coverage.sh # coverage kcov
  - cd .. || exit 1
  - cd docs || exit 1
  - bash generate_docs.sh docs.sh # documentation shdoc
  - cd .. || exit 1

notifications:
    email: false