language: bash
dist: bionic

before_cache:
  - bash coverage.sh
cache:
  directories:
    - tests/bin
    - tests/coverage

addons:
  apt:
    sources:
      - sourceline: 'ppa:duggan/bats'
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev
      - build-essential
      - bats
      - bc
      
before_install:
  # install all the submodules
  - git submodule update --init --recursive
  - git pull --recurse-submodules
  - git submodule update --remote

script:
  - cd tests 
  - bash linter.sh # linter shellcheck
  - bash coverage.sh # coverage kcov
  - cd ..
  - cd docs
  - bash generate_docs.sh docs.sh # documentation shdoc
  - cd ..

notifications:
    email: false