version: "3"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
      - GUAC_USER=abc #optional
      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
    volumes:
      - /home/udocker/calibre/config:/config
    ports:
      - 8001:8080
      - 8002:8081
    restart: unless-stopped