version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    # user: udocker
    networks:
      - gitea
    volumes:
      - /home/udocker/volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=gitea"