version: "3.3"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/docker/tautulli/config:/config
      - /home/docker/plex/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped