version: "3.3"
services:
  wine-vnc:
    image: "msjpq/wine-vnc:bionic"
    container_name: kdedocker
    environment: 
     - SCR_WIDTH=1600
     - SCR_HEIGHT=900
     - PATH_PREFIX=/
     - VNC_RESIZE=remote
     - RECON_DELAY=250
     - PAGE_TITLE=kdedocker
     - ROOT_PASSWORD=root
    ports:
      - "8100:8080"
      - "5900:5900"
    volumes: 
      - /home/udocker/kdedocker/appconfig:/root
