version: "3.7"
services:
  dailynotes:
    image: m0ngr31/dailynotes
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    ports:
      - "5000:5000"
    volumes:
      - "/home/udocker/volumes/config:/app/config"
    restart: unless-stopped
