version: '3.7'
services:
    odoo:
        image: odoo:12.0
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
        restart: unless-stopped
        labels:
            - "AIS.traefik=false"
            - "AIS.name=odoo"
    odoo_db:
        image: postgres:10
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
        restart: unless-stopped
        labels:
            - "AIS.traefik=false"
            - "AIS.name=odoo_db"