version: "3.7"
services:
  osjs:
    image: "osjs/osjs:v3"
    container_name: osjs
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    ports:
      - "7999:8000"
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=osjs"
