version: "3.7"
services:
  opentogethertube:
    image: antoine13/opentogethertube
    container_name: opentogethertube
    environment:
      - YOUTUBE_API_KEY=API_KEY_GOES_HERE # change me
      # redis
      - REDIS_HOST=redis_db
      # postgres
      - POSTGRES_DB_USERNAME=opentogethertube
      - POSTGRES_DB_NAME=opentogethertube
      - POSTGRES_DB_HOST=postgres_db
      - POSTGRES_DB_PASSWORD=postgres
    ports:
      - 6666:8080
    links:
      - redis_db
      - postgres_db
    depends_on:
      - redis_db
      - postgres_db
    labels:
      - "AIS.traefik=false"
      - "AIS.name=opentogethertube"

  redis_db:
    container_name: opentogethertube_redis
    image: redis
    healthcheck:
      test: "redis-cli ping"
    expose:
      - 6379
    volumes:
      - /home/udocker/opentogethertube/redis:/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.traefik=false"
      - "AIS.name=opentogethertube_redis"

  postgres_db:
    container_name: opentogethertube_postgres
    image: postgres
    environment:
      - POSTGRES_DB=opentogethertube
      - POSTGRES_USER=opentogethertube
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp
    healthcheck:
      test: "pg_isready -U opentogethertube"
    expose:
      - 5432
    volumes:
      - /home/udocker/opentogethertube/db:/var/lib/postgresql/data
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.traefik=false"
      - "AIS.name=opentogethertube_postgres"
