version: '3.3'
services:
    nginx-fpm-alpine:
        image: 'privatebin/nginx-fpm-alpine:1.5.1'
        container_name: privatebin
        # user: udocker
        environment:
            - PUID='${UDOCKER_USERID}'
            - PGID='${UDOCKER_GROUPID}'
            - TZ='${TZ}'
        ports:
            - '8052:80'
        volumes:
            - '/home/udocker/volumes/privatebin/conf.php:/srv/cfg/conf.php:ro'
            - '/home/udocker/volumes/privatebin/data:/srv/data'
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        labels:
            - "AIS.name=privatebin"