version: "3.3"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/piwigo/config:/config
    ports:
      - 8049:80
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=piwigo"