version: '2'

services:
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: always
        networks:
            - media        
        ports:
            - 9117:9117
        volumes:
            - /srv/downloads:/downloads
            - /srv/appdata/jackett:/config
        environment:
            PUID: ${userid}
            PGID: ${groupid}
            TZ: ${time}

networks:
    media:
        external: true    