version: "3.3"
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    user: udocker
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    volumes:
      - /home/udocker/volumes/openvpn/conf:/etc/openvpn
