# https://blog.gostew.art/automating-home-tv-show-streaming/
version: '3.7'
services:
  torrent:
    container_name: qbittorent-vpn
    image: markusmcnugen/qbittorrentvpn
    network_mode: "service:qbittorent-vpn"
    ports:
      - 8080:8080
      - 6969:6969
      - 6969:6969/udp
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    volumes:
      - ./torrent:/config
      - ./media:/downloads
    environment:
      VPN_ENABLED: 'yes'
      LAN_NETWORK: 192.168.1.0/24
      NAME_SERVERS: 8.8.8.8,8.8.4.4
      INCOMING_PORT_ENV: 6969
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    network_mode: "service:plex"
    environment:
      - TZ=America/New_York
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - ./media:/data
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./sonarr:/config
      - ./media/TV:/tv
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    network_mode: "service:jackett"
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./jackett:/config