version: "3.3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    user: udocker
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
      - UMASK_SET=022 #optional
    volumes:
      - /home/udocker/volumes/plex/config:/config
      - /home/udocker/volumes//tvseries:/tv
      - /home/udocker/volumes//movies:/movies
      - /home/udocker/volumes//plex/transcode:/transcode
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=plex"