version: '3.7'
services:
    mosquitto:
        image: eclipse-mosquitto
        hostname: mqtt
        container_name: mqtt
        ports:
          - '1883:1883'
          - '9001:9001'
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - /home/udocker/volumes/mqtt/config:/mosquitto/config
            - /home/udocker/volumes/mqtt/data:/mosquitto/data
            - /home/udocker/volumes/mqtt/log:/mosquitto/log
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        labels:
            - "AIS.name=mqtt"
