version: "3.3"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    volumes:
      - /home/udocker/volumes/tautulli/config:/config
      - /home/udocker/volumes/plex/logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
        - "AIS.traefik=false"
        - "AIS.name=tautulli"

