version: '3.3'
services:
    jackett:
        image: linuxserver/jackett
        container_name: jackett
    ports:
        - 9117:9117
    # environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=America/New_York
    volumes:
        - ./jackett:/config