Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eaon64"
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |v|
    v.name = "eaon64_another-install-script"
    v.memory = 4096
    v.cpus = 2
  end

end