Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |v|
    v.name = "xenial64_another-install-script"
    config.vm.box_version = "20200320.0.0"
    v.customize [ "modifyvm", :id, "--uartmode1", "file", File.join("C:/Users/Antoine/", "ubuntu-xenial-16.04-cloudimg-console.log") ]
    config.vm.synced_folder ".", "/vagrant", disabled: true
    v.memory = 4096
    v.cpus = 2

    # config.vm.network "forwarded_port", guest: 4040, host: 4040
    # config.vm.network "forwarded_port", guest: 8000, host: 8000
    # config.vm.network "forwarded_port", guest: 6875, host: 8080
    # config.vm.network "forwarded_port", guest: 8001, host: 8001
    # config.vm.network "forwarded_port", guest: 6889, host: 6889
    # config.vm.network "forwarded_port", guest: 8003, host: 8003
    # config.vm.network "forwarded_port", guest: 5050, host: 5050
    # config.vm.network "forwarded_port", guest: 8004, host: 8004
    # config.vm.network "forwarded_port", guest: 8005, host: 8005
    # config.vm.network "forwarded_port", guest: 8200, host: 8200
    # config.vm.network "forwarded_port", guest: 8200, host: 8200
    # config.vm.network "forwarded_port", guest: 8006, host: 8006
    # config.vm.network "forwarded_port", guest: 8007, host: 8007
    # config.vm.network "forwarded_port", guest: 8008, host: 8008
    # config.vm.network "forwarded_port", guest: 8009, host: 8009
    # config.vm.network "forwarded_port", guest: 8011, host: 8011
    # config.vm.network "forwarded_port", guest: 8012, host: 8012
    # config.vm.network "forwarded_port", guest: 8181, host: 8181
    # config.vm.network "forwarded_port", guest: 8080, host: 8080
    # config.vm.network "forwarded_port", guest: 8013, host: 8013
    # config.vm.network "forwarded_port", guest: 8014, host: 8014
    # config.vm.network "forwarded_port", guest: 8096, host: 8096
    # config.vm.network "forwarded_port", guest: 8015, host: 8015
    # config.vm.network "forwarded_port", guest: 8888, host: 8888
    # config.vm.network "forwarded_port", guest: 8030, host: 8030
    # config.vm.network "forwarded_port", guest: 8031, host: 8031
    # config.vm.network "forwarded_port", guest: 8339, host: 8339
    # config.vm.network "forwarded_port", guest: 8034, host: 8034

    # config.vm.network "forwarded_port", guest: 8035 , host: 8035
    # config.vm.network "forwarded_port", guest: 8036, host:  8036
    # config.vm.network "forwarded_port", guest: 8037, host: 8037
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    # config.vm.network "forwarded_port", guest: , host: 
    
  end
end