version: "3.3"
services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    user: udocker
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    volumes:
      - /home/udocker/volumes/medusa/config:/config
      - /home/udocker/volumes/medusa/downloads:/downloads
      - /home/udocker/volumes/medusa/tv:/tv
    ports:
      - 8038:8081
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=medusa"
