version: "3.3"
services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    volumes:
      - /home/udocker/volumes/piwigo/config:/config
    ports:
      - 8049:80
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=piwigo"