version: "3"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    user: udocker
    environment:
      - PUID: ${UDOCKER_USERID}
      - PGID: ${UDOCKER_GROUPID}
      - TZ: ${TZ}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/udocker/volumes/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID: ${UDOCKER_USERID}
      - PGID: ${UDOCKER_GROUPID}
      - TZ: ${TZ}
      - MYSQL_ROOT_PASSWORD=bookstack
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /home/udocker/volumes/bookstack/db/config:/config
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=bookstack"
