version: '3.3'
services:
    minecraft:
        image: itzg/minecraft-server
        # user: udocker
        container_name: minecraft
        ports:
            - '25565:25565'
        environment:
          - EULA: "TRUE"
          - PVP=true
          - DIFFICULTY=easy
          - PUID='${UDOCKER_USERID}'
          - PGID='${UDOCKER_GROUPID}'
          - TZ='${TZ}'
        volume:
          - /home/udocker/volumes/minecraft:/data
        tty: true
        stdin_open: true
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        labels:
          - "AIS.name=minecraft"
