version: "3.3"
services:
  huginn:
    image: huginn/huginn
    container_name: huginn
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    ports:
      - "8013:3000"
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=heimdall"
