version: '3.3'
services:
  redis:
    image: redis
    container_name: open-streaming-platform_db
    expose:
      - 6379
  app:
    build: .
    restart: always
    ports:
      - '1935:1935'
      - '8585:80'
      - '8553:443'
    env:
      - REDIS_HOST="open-streaming-platform"
      - REDIS_PORT=6379
      - REDIS_PASSWORD="open-streaming-platform"
