version: "3.7"

services:
simple-traefik-dash:
  image: msjpq/simple-traefik-dash
  labels:
    - traefik.http.services.std.loadbalancer.server.port=5050
    - traefik.http.routers.std.tls.options=default
    - traefik.http.routers.std.rule=Host("<Something>")
  environment:
    - STD_TRAEFIK_API=http://traefik:8080/ # Required, make sure you can actually talk to Traefik
    - STD_TRAEFIK_ENTRY_POINTS=web-secure # Required, only routes using entrypoints will be parsed
    - STD_TRAEFIK_EXIT_PORT=443 # Required, your exit port
    - STD_KUBECRD_FIX=True # Optional, enable if you see <ns>-name-<randomstring> with in Kubernetes

    - STD_TITLE=🐳 # Optional, page title
    - STD_BACKGROUND=https://... # Optional, changes the background image
    - STD_PATH_PREFIX=/std # Optional, for reverse proxy
  volumes:
    - ./more.csv:/std/more-routes/more.csv # Optional - CSV Columns: name, uri
    - ./ignore.csv:/std/ignore-routes/ignore.csv # Optional - CSV Column: name
