 grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    # user: "0"
    ports:
      - 3000:3000
    env_file:
      - grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana