version: "3.3"

services:
  app:
    image: monicahq/monicahq
    container_name: monica
    # user: udocker
    depends_on:
      - mysql
    ports:
      - 8039:80
    environment:
      - APP_KEY=kENAi5LPto3rMXO1OXDV7H9GEqOSkIpn
      - DB_HOST=mysql
    volumes:
      - /home/udocker/volumes/monica:/var/www/monica/storage
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=monica"

  mysql:
    image: mysql:5.7
    container_name: monica_db
    # user: udocker
    environment:
      - MYSQL_ROOT_PASSWORD=monica
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/monica/db:/var/lib/mysql
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=monica_db"

volumes:
  data:
    name: data
  mysql:
    name: mysql