version: "3.3"
services:
  headphones:
    image: linuxserver/headphones
    container_name: headphones
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/headphones/config:/config
      - /home/udocker/volumes/headphones/downloads:/downloads
      - /home/udocker/volumes/headphones/music:/music
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=guacamole"    
