version: '3.3'
services:
  neko:
    image: nurdism/neko
    restart: always
    shm_size: '1gb'
    ports:
      - "8032:8080"
    environment:
      NEKO_DISPLAY: 0
      NEKO_WIDTH: 1280
      NEKO_HEIGHT: 720
      NEKO_PASSWORD: neko
      NEKO_BIND: :8080