version: "3"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    user: udocker
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    volumes:
      - /home/udocker/volumes/freshrss/config:/config
    ports:
      - 8007:80
    restart: unless-stopped
