version: '3.3'
services:
    nginx-fpm-alpine:
      container_name: privatebin
      restart: always
      ports:
          - '8080:80'
      volumes:
          - 'conf.php:/srv/cfg/conf.php:ro'
          - '/home/udocker/privatebin/data:/srv/data'
      image: 'privatebin/nginx-fpm-alpine:1.3.1'