# https://hub.docker.com/r/linuxserver/heimdall/
version: "3.3"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${PATH_CONFIG}:/config
    ports:
      - ${PORT_WEB}:80
