version: "3.3"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    user: udocker
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    volumes:
      - /home/udocker/heimdall/config:/config
    ports:
      - 8080:80
      - 443:443
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=heimdall"
