version: "3.7"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    volumes:
      - /dev/net:/dev/net:z # tun device
      - /home/udocker/volumes/htpc-download-box/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network
    command: '-f "" -r 192.168.1.0/24' # enable firewall and route local network traffic
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/htpc-download-box/downloads:/downloads # downloads folder
      - /home/udocker/volumes/htpc-download-box/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: host
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/udocker/volumes/htpc-download-box/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - /home/udocker/volumes/htpc-download-box/config/jackett:/config # config files

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: host
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/htpc-download-box/downloads:/downloads # download folder
      - /home/udocker/volumes/htpc-download-box/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: host
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/udocker/volumes/htpc-download-box/config/sonarr:/config # config files
      - /home/udocker/volumes/htpc-download-box/complete/tv:/tv # tv shows folder
      - /home/udocker/volumes/htpc-download-box/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    network_mode: host
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/udocker/volumes/htpc-download-box/config/radarr:/config # config files
      - /home/udocker/volumes/htpc-download-box/complete/movies:/movies # movies folder
      - /home/udocker/volumes/htpc-download-box/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
      - TZ='${TZ}'
    network_mode: host
    volumes:
      - /home/udocker/volumes/htpc-download-box/config/plex:/config # plex database
      - /home/udocker/volumes/htpc-download-box/plex/transcode:/transcode # temp transcoded files
      - /home/udocker/volumes/htpc-download-box/plex/data:/data # media library
      - /home/udocker/volumes/htpc-download-box/plex/logs:/logs
    labels:
      - "AIS.name=htpc-download-box-plex"

    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      environment:
        - PUID='${UDOCKER_USERID}'
        - PGID='${UDOCKER_GROUPID}'
        - TZ='${TZ}'
      volumes:
        - /home/udocker/volumes/htpc-download-box/config/tautulli:/config
        - /home/udocker/volumes/htpc-download-box/plex/logs:/logs
      network_mode: host
      ports:
        - 8063:8181
      restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
      labels:
        - "AIS.name=htpc-download-box-tautulli"
