version: "2"
services:
  mylar:
  image: linuxserver/mylar
  container_name: mylar
  environment:
    - PUID: ${UDOCKER_USERID}
    - PGID: ${UDOCKER_GROUPID}
    - TZ: ${TZ}
  volumes:
    - /home/udocker/volumes/mylar/config:/config
    - /home/udocker/volumes/mylar/comics:/comics
    - /home/udocker/volumes/mylar/downloads:/downloads
  ports:
    - 8090:8090
  restart: unless-stopped
