# https://github.com/firefly-iii/docker

version: "3.3"
services: 
  firefly_iii_app:
    image: jc5x/firefly-iii:latest
    container_name: firefly-iii
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "8006:80"
    env_file: firefly_iii.env
    labels:
        - "AIS.name=firefly-iii"
    volumes: 
      - firefly_iii_export:/var/www/firefly-iii/storage/export
      - firefly_iii_upload:/var/www/firefly-iii/storage/upload
  firefly_iii_db: 
    image: "postgres:16"
    container_name: firefly_iii_db
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=firefly
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
    labels:
      - "AIS.name=firefly-iii_db"

networks: 
  firefly_iii_net: 
    driver: bridge

volumes: 
  firefly_iii_db: /home/udocker/volumes/firefly-iii/db
  firefly_iii_export: /home/udocker/volumes/firefly-iii/export
  firefly_iii_upload: /home/udocker/volumes/firefly-iii/upload