version: '3.3'
services:
    syncthing:
        image: 'syncthing/syncthing:latest'
        # user: udocker
        environment:
            - PUID='${UDOCKER_USERID}'
            - PGID='${UDOCKER_GROUPID}'
            - TZ='${TZ}'
        container_name: syncthing
        ports:
            - '8384:8384'
            - '22000:22000'
        volumes:
            - '/home/udocker/volumes/syncthing:/var/syncthing'
        restart: unless-stopped
        labels:
            - "AIS.traefik=false"
            - "AIS.name=udocker"