version: "3.3"
services:
  medusa:
    image: linuxserver/medusa
    container_name: medusa
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/medusa/config:/config
      - /home/udocker/volumes/medusa/downloads:/downloads
      - /home/udocker/volumes/medusa/tv:/tv
    ports:
      - 8038:8081
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=medusa"
