version: '3.3'
services:
    mcmyadmin2:
        image: linuxserver/mcmyadmin2
        container_name: mcmyadmin
        # user: udocker
        environment:
            - PUID='${UDOCKER_USERID}'
            - PGID='${UDOCKER_GROUPID}'
            - TZ='${TZ}'
        volumes:
            - '/home/udocker/volumes/mcmyadmin:/minecraft'
        ports:
            - '8037:8080'
            - '25565:25565'
        restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
        labels:
            - "AIS.name=mcmyadmin"