version: "3"

services:
  code-server:
    image: codercom/code-server
    container_name: code-server
    user: udocker
    environment:
      - PASSWORD: coder
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    ports:
      - "8003:8080"
    volumes:
      - /home/udocker/volumes/code-server/project:/home/coder/project
      - /home/udocker/.local/share/code-server:/home/coder/.local/share/code-server
    restart: unless-stopped