version: '3.3'
services:
  cyberchef:
    image: 4nxio/cyberchef:latest
    container_name: cyberchef
    user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    ports:
      - 8004:80
    volumes:
      - /home/udocker/volumes/cyberchef/cyberchef-nginx:/etc/nginx
      - /home/udocker/volumes/cyberchef/cyberchef-ssl:/etc/ssl
      - /home/udocker/volumes/cyberchef/cyberchef-logs:/var/log/nginx
    restart: unless-stopped
    labels:
        - "AIS.traefik=false"
        - "AIS.name=cyberchef"