version: '3.3'
services:
    jenkins:
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - '$jenkins_data:/var/jenkins_home'
        image: 'jenkins/jenkins:lts'