
version: "3.7"
services:
  emby:
    image: linuxserver/emby
    container_name: emby
    environment:
    - PUID='${UDOCKER_USERID}'
    - PGID='${UDOCKER_GROUPID}'
    - TZ='${TZ}'
      - UMASK_SET=022 #optional
    volumes:
      - /home/udocker/volumes/emby/config:/config
      - /home/udocker/volumes/emby/tvshows:/data/tvshows
      - /home/udocker/volumes/emby/movies:/data/movies
      - /home/udocker/volumes/emby/transcode:/transcode #optional
      - /home/udocker/volumes/emby/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    # devices:
    #   - /dev/dri:/dev/dri #optional
    #   - /dev/vchiq:/dev/vchiq #optional
    #   - /dev/video10:/dev/video10 #optional
    #   - /dev/video11:/dev/video11 #optional
    #   - /dev/video12:/dev/video12 #optional
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=emby"