version: '3.3'
services:
    syncthing:
        container_name: syncthing
        ports:
            - '8384:8384'
            - '22000:22000'
        volumes:
            - '$PATH_SYNC:/var/syncthing'
        image: 'syncthing/syncthing:latest'