Vagrant.configure("2") do |config|
    config.vm.box = "generic/rhel7"
    # config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
  
    config.vm.provider "virtualbox" do |v|
      v.name = "rhel7_another-install-script"
      config.vm.synced_folder ".", "/vagrant", disabled: true
      v.memory = 4096
      v.cpus = 2
    end
  end