version: "3"
services:
    .template:
        image: .template
        container_name: .template
        environment:
            - PUID: ${userid}
            - PGID: ${groupid}
            - TZ: ${time}
        volumes:
        ports:
        restart: unless-stopped
