version: "3.3"
services:
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/tautulli/config:/config
      - /home/udocker/volumes/plex/logs:/logs
    ports:
      - 8063:8181
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
        
        - "AIS.name=tautulli"

