version: '3'

services:
  # https://hub.docker.com/r/linuxserver/heimdall/
  heimdall:
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    volumes:
    - ./config:/config
    ports:
    - 8080:80
    # - 8443:443
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New York