$script = <<-SCRIPT
pacman -Syy --noconfirm
pacman -Syu --noconfirm git
git clone https://github.com/antoinebou13/another-install-script
SCRIPT


Vagrant.configure("2") do |config|
    config.vm.box = "archlinux/archlinux"
    config.vm.provision "shell", inline: $script
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
  
    config.vm.provider "virtualbox" do |v|
      v.name = "archlinux_another-install-script"
      config.vm.synced_folder ".", "/vagrant", disabled: true
      v.memory = 4096
      v.cpus = 2
    end
  end