version: "3.7"

services:
  app:
    image: monicahq/monicahq
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - APP_KEY=
      - DB_HOST=mysql
    volumes:
      - data:/var/www/monica/storage
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql