# https://github.com/firefly-iii/docker
version: "3"
networks: 
  firefly_iii_net: 
    driver: bridge
services: 
  firefly_iii_app:
    container_name: firefly-iii
    image: jc5x/firefly-iii:latest
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "8006:80"
    env_file: firefly_iii.env
    volumes: 
      - 
        source: firefly_iii_export
        target: ${PATH_EXPORT}
        type: volume
      - 
        source: firefly_iii_upload
        target: ${PATH_UPLOAD}
        type: volume
  firefly_iii_db: 
    image: "postgres:10"
    container_name: firefly_iii_db
    environment:
      - PUID: ${userid}
      - PGID: ${groupid}
      - TZ: ${time}
      - POSTGRES_PASSWORD=firefly
      - POSTGRES_USER=firefly
    networks: 
      - firefly_iii_net
    volumes: 
      - /home/udocker/firefly_iii/db:/var/lib/postgresql/data
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~