version: "3.7"
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    # user: udocker
    environment:
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - /home/udocker/volumes/grocy:/config
    ports:
      - 9283:80
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    labels:
      - "AIS.name=grocy"