version: '3.7'
services:
    webserver:
        build: ./
        # uncomment the following line to start automatically on system boot
        # restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8056:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - ./consume:/consume
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_USE_SSL=false
            - PAPERLESS_OCR_LANGUAGES=eng
        command: ["gunicorn", "-b", "0.0.0.0:8000"]

    consumer:
        build: ./
        restart: always
        depends_on:
            webserver:
                condition: service_healthy
        volumes:
            - /home/paperless/data:/usr/src/paperless/data
            - /home/paperless/media:/usr/src/paperless/media
            - /home/paperless/consume:/consume
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media: