version: '3.3'
services:
    guacamole:
        image: guacamole
        container_name: guacamole
        environment:
            - PUID: ${userid}
            - PGID: ${groupid}
            - TZ: ${time}
        ports:
            - '8012:8080'
        volumes:
            - '/home/udocker/guacamole/config:/configoznu/guacamole'
        restart: unless-stopped