version: "2"
services:
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    user: udocker
    environment:
      - PUID: ${UDOCKER_USERID}
      - PGID: ${UDOCKER_GROUPID}
      - TZ: ${TZ}
      - UMASK_SET=022
    volumes:
      - /home/udocker/volumes/couchpotato/config:/config
      - /home/udocker/volumes/couchpotato/downloads:/downloads
      - /home/udocker/volumes/couchpotato/movies:/movies
    ports:
      - 5050:5050
    restart: unless-stopped
    labels:
        - "AIS.traefik=false"
        - "AIS.name=couchpotato"