version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    # user: udocker
    environment:
      - KOMGA_LIBRARIES_SCAN_DIRECTORY_EXCLUSIONS=#recycle,@eaDir
      - PUID='${UDOCKER_USERID}'
      - PGID='${UDOCKER_GROUPID}'
      - TZ='${TZ}'
    volumes:
      - type: bind
        source: /home/udocker/volumes/komga/config
        target: /config
      - type: bind
        source: /home/udocker/volumes/komga/books
        target: /books
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - "AIS.traefik=false"
      - "AIS.name=komga"